version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "5051:5051"
    env_file:
      - .env
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-client
  #   ports:
  #     - "5052:5051"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - server
